# Generated by Django 5.0.9 on 2026-09-04 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='code',
            field=models.CharField(help_text="Stable identifier used in code, e.g. 'user.login'.", max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._-]+$', 'Use letters, numbers, dots, underscores or hyphens only.')]),
        ),
    ]
